version: "3"
services:
  curriculum-front:
    image: index.docker.io/fuze365/curriculum-front:latest
    ports:
      - "8080:8080"
  curriculum-back:
    image: index.docker.io/fuze365/curriculum-back:latest
    ports:
      - "3000:3000"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 30
