name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
  push:
    branches:
      - master

steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Build and push Docker image for back-end
    uses: docker/build-push-action@v1
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      repository: fuze365/curriculum-front
      dockerfile: curriculum-back/Dockerfile
      tags: latest

  - name: Build and push Docker image for front-end
    uses: docker/build-push-action@v1
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      repository: fuze365/curriculum-back
      dockerfile: curriculum-front/Dockerfile
      tags: latest
